# Generated by Django 5.0.1 on 2026-06-08 16:11

import directory.models.Histograms
import directory.models.Trained_Model
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_id', models.IntegerField()),
                ('context', models.TextField(default=None)),
                ('context_title', models.TextField(default=None)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('uploader', 'context_id')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.TextField(default=None)),
                ('question', models.TextField(default=None)),
                ('target_level', models.TextField(default=None)),
                ('question_difficulty', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('question_discrimination', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('question_facility', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.context')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(default=None)),
                ('is_correct', models.BooleanField(default=False)),
                ('question_linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='directory.question')),
            ],
        ),
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('public', models.BooleanField(default=False)),
                ('parameter', models.CharField(choices=[('difficulty', 'Difficulty'), ('discrimination', 'Discrimination'), ('facility', 'Facility')], default=None, max_length=63)),
                ('pickle_file', models.FileField(upload_to=directory.models.Trained_Model.pickle_file_path)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('std_error', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('median', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('mode', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('std_deviation', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('kurtosis', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('skewness', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('minimum', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('maximum', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('range', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('model_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='directory.trainedmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=4, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parameter', models.CharField(choices=[('difficulty', 'Difficulty'), ('discrimination', 'Discrimination'), ('facility', 'Facility')], default=None, max_length=63)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.question')),
                ('model_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.trainedmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Histogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_image', models.ImageField(upload_to=directory.models.Histograms.histograms_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('model_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histograms', to='directory.trainedmodel')),
            ],
        ),
    ]
