# Generated by Django 5.0.1 on 2026-02-23 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_id', models.IntegerField()),
                ('context', models.TextField(default=None)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('uploader', 'context_id')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.TextField(default=None)),
                ('question', models.TextField(default=None)),
                ('target_level', models.TextField(default=None)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.context')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(default=None)),
                ('is_correct', models.BooleanField(default=False)),
                ('question_linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='directory.question')),
            ],
        ),
    ]
