# Generated by Django 6.0 on 2026-01-08 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default=None, max_length=516)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(default=None)),
                ('is_correct', models.BooleanField(default=False)),
                ('question_linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='directory.question')),
            ],
        ),
    ]
