# Generated by Django 5.0.1 on 2026-05-21 18:53

import directory.models.Histograms
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Histogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_image', models.ImageField(upload_to=directory.models.Histograms.histograms_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.trainedmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
