# Generated by Django 5.0.1 on 2026-02-23 16:13

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='context',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelManagers(
            name='context',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
