# Generated by Django 6.0.2 on 2026-02-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_difficulty',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_discrimination',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_facility',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True),
        ),
    ]
