# Generated by Django 5.0.1 on 2026-05-23 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_histogram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='topic_name',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='question',
        ),
        migrations.DeleteModel(
            name='TopicNames',
        ),
        migrations.DeleteModel(
            name='Topics',
        ),
    ]
