# Generated by Django 6.0.2 on 2026-02-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_alter_question_question_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_difficulty',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_discrimination',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_facility',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=6, null=True),
        ),
    ]
