# Generated by Django 5.0.1 on 2026-05-24 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_remove_topics_topic_name_remove_topics_question_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean', models.DecimalField(decimal_places=4, max_digits=6)),
                ('std_error', models.DecimalField(decimal_places=4, max_digits=6)),
                ('median', models.DecimalField(decimal_places=4, max_digits=6)),
                ('mode', models.DecimalField(decimal_places=4, max_digits=6)),
                ('std_deviation', models.DecimalField(decimal_places=4, max_digits=6)),
                ('variance', models.DecimalField(decimal_places=4, max_digits=6)),
                ('kurtosis', models.DecimalField(decimal_places=4, max_digits=6)),
                ('skewness', models.DecimalField(decimal_places=4, max_digits=6)),
                ('minimum', models.DecimalField(decimal_places=4, max_digits=6)),
                ('maximum', models.DecimalField(decimal_places=4, max_digits=6)),
                ('range', models.DecimalField(decimal_places=4, max_digits=6)),
                ('count', models.IntegerField()),
                ('model_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.trainedmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
