# Generated by Django 5.0.1 on 2026-05-24 02:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_statistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
