# Generated by Django 5.0.1 on 2026-05-24 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_statistic_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='kurtosis',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='maximum',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='mean',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='median',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='minimum',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='mode',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='range',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='skewness',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='std_deviation',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='std_error',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='variance',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
