# Generated by Django 6.0.2 on 2026-02-26 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_alter_question_question_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.question', unique=True),
        ),
    ]
