# Generated by Django 5.0.1 on 2026-05-24 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_alter_statistic_kurtosis_alter_statistic_maximum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histogram',
            name='model_used',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histograms', to='directory.trainedmodel'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='model_used',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='directory.trainedmodel'),
        ),
    ]
