# Generated by Django 6.0.2 on 2026-03-09 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_alter_topics_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='directory.question'),
        ),
    ]
